### ISSUE TITLE
uninitialized constant Blueprinter::Transformer

### ISSUE THREAD

**Issue by slhck** [procore/blueprinter#173]
I'm trying to implement a transformer like so:

In `app/serializers/transformers/polymorphic_transformer.rb`:

```
class PolymorphicTransformer < Blueprinter::Transformer
  def transform(hash, object, options)
    hash["#{object.geolocationable_type.underscore}_id"] = object.geolocationable_id
  end
end
```

And in the serializer `app/serializers/geolocation_blueprint.rb`:

```
require 'transformers/polymorphic_transformer.rb'

class GeolocationBlueprint < Blueprinter::Base
  identifier :id
  transform PolymorphicTransformer
end

```

But I get:

```
Traceback (most recent call last):
        4: from (irb):53
        3: from (irb):53:in `rescue in irb_binding'
        2: from app/serializers/geolocation_blueprint.rb:1:in `<main>'
        1: from app/serializers/transformers/polymorphic_transformer.rb:1:in `<main>'
NameError (uninitialized constant Blueprinter::Transformer)
```

I am using blueprinter 0.18.0. Any idea what I'm doing wrong?

**Comment by slhck** [comment]
Oh, never mind, I see this is a feature since 0.19 that I just missed.

**Comment by slhck** [comment]
Perhaps it's interesting for some folks… a generic polymorphic transformer that inserts the required foreign keys and IDs:

```
class PolymorphicTransformer < Blueprinter::Transformer
  def transform(hash, object, options)
    object.class.reflect_on_all_associations.each do |reflection|
      next unless reflection.options[:polymorphic]
      foreign_type = object.send(reflection.foreign_type).underscore
      hash["#{foreign_type}_id"] = object.send(reflection.foreign_key)
    end
  end
end
```

**Comment by philipqnguyen** [comment]
Thanks for sharing =)
